repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
        args:
        -   --unsafe
    -   id: check-symlinks
    -   id: check-added-large-files
    -   id: detect-private-key

-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.4.0post1
    hooks:
    -   id: pre-commit-update

-   repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
    -   id: commitizen
